<a href="https://colab.research.google.com/github/ryukirisame/crop-yield-prediction/blob/main/crop%20yield%20predict_2.0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [199]:
import numpy as np 
import pandas as pd 

# **DATA PREPROCESSING**

### **WORKING ON YIELD DATA**

In [200]:
df_yield = pd.read_csv('yield.csv')
df_yield.shape

(56717, 12)

In [201]:
df_yield.head()

Domain Code Domain  Area Code         Area  Element Code Element  Item Code  \
0          QC  Crops          2  Afghanistan          5419   Yield         56   
1          QC  Crops          2  Afghanistan          5419   Yield         56   
2          QC  Crops          2  Afghanistan          5419   Yield         56   
3          QC  Crops          2  Afghanistan          5419   Yield         56   
4          QC  Crops          2  Afghanistan          5419   Yield         56   

    Item  Year Code  Year   Unit  Value  
0  Maize       1961  1961  hg/ha  14000  
1  Maize       1962  1962  hg/ha  14000  
2  Maize       1963  1963  hg/ha  14260  
3  Maize       1964  1964  hg/ha  14257  
4  Maize       1965  1965  hg/ha  14400

In [202]:
# RENAMING Value field to hg/ha_yield
df_yield = df_yield.rename(index=str, columns={"Value": "hg/ha_yield"})
df_yield.head()

Domain Code Domain  Area Code         Area  Element Code Element  Item Code  \
0          QC  Crops          2  Afghanistan          5419   Yield         56   
1          QC  Crops          2  Afghanistan          5419   Yield         56   
2          QC  Crops          2  Afghanistan          5419   Yield         56   
3          QC  Crops          2  Afghanistan          5419   Yield         56   
4          QC  Crops          2  Afghanistan          5419   Yield         56   

    Item  Year Code  Year   Unit  hg/ha_yield  
0  Maize       1961  1961  hg/ha        14000  
1  Maize       1962  1962  hg/ha        14000  
2  Maize       1963  1963  hg/ha        14260  
3  Maize       1964  1964  hg/ha        14257  
4  Maize       1965  1965  hg/ha        14400

In [203]:
# dropping unwanted columns.
df_yield = df_yield.drop(['Year Code','Element Code','Element','Year Code','Area Code','Domain Code','Domain','Unit','Item Code'], axis=1)
df_yield.head()

Area   Item  Year  hg/ha_yield
0  Afghanistan  Maize  1961        14000
1  Afghanistan  Maize  1962        14000
2  Afghanistan  Maize  1963        14260
3  Afghanistan  Maize  1964        14257
4  Afghanistan  Maize  1965        14400

In [204]:
df_yield.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56717 entries, 0 to 56716
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Area         56717 non-null  object
 1   Item         56717 non-null  object
 2   Year         56717 non-null  int64 
 3   hg/ha_yield  56717 non-null  int64 
dtypes: int64(2), object(2)
memory usage: 2.2+ MB


###**WORKING ON RAINFALL DATA**

In [205]:
df_rain = pd.read_csv('rainfall.csv')
df_rain.head()

Area  Year average_rain_fall_mm_per_year
0  Afghanistan  1985                           327
1  Afghanistan  1986                           327
2  Afghanistan  1987                           327
3  Afghanistan  1989                           327
4  Afghanistan  1990                           327

In [206]:
df_rain = df_rain.rename(index=str, columns={" Area": 'Area'})

In [207]:
# checking data types 
df_rain.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6727 entries, 0 to 6726
Data columns (total 3 columns):
 #   Column                         Non-Null Count  Dtype 
---  ------                         --------------  ----- 
 0   Area                           6727 non-null   object
 1   Year                           6727 non-null   int64 
 2   average_rain_fall_mm_per_year  5953 non-null   object
dtypes: int64(1), object(2)
memory usage: 210.2+ KB


In [208]:
# converting average_rain_fall_mm_per_year from object to float
df_rain['average_rain_fall_mm_per_year'] = pd.to_numeric(df_rain['average_rain_fall_mm_per_year'],errors = 'coerce')
df_rain.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6727 entries, 0 to 6726
Data columns (total 3 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Area                           6727 non-null   object 
 1   Year                           6727 non-null   int64  
 2   average_rain_fall_mm_per_year  5947 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 210.2+ KB


In [209]:
df_rain = df_rain.dropna()

In [210]:
df_rain.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5947 entries, 0 to 6726
Data columns (total 3 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Area                           5947 non-null   object 
 1   Year                           5947 non-null   int64  
 2   average_rain_fall_mm_per_year  5947 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 185.8+ KB


In [ ]:
df_rain.describe()

Year  average_rain_fall_mm_per_year
count  5947.000000                    5947.000000
mean   2001.365899                    1124.743232
std       9.526335                     786.257365
min    1985.000000                      51.000000
25%    1993.000000                     534.000000
50%    2001.000000                    1010.000000
75%    2010.000000                    1651.000000
max    2017.000000                    3240.000000

In [211]:
# merge yield dataframe with rain dataframe by year and area columns 
yield_df = pd.merge(df_yield, df_rain, on=['Year','Area'])

In [ ]:
yield_df.shape

(25385, 5)

In [212]:
yield_df.head()

Area         Item  Year  hg/ha_yield  average_rain_fall_mm_per_year
0  Afghanistan        Maize  1985        16652                          327.0
1  Afghanistan     Potatoes  1985       140909                          327.0
2  Afghanistan  Rice, paddy  1985        22482                          327.0
3  Afghanistan        Wheat  1985        12277                          327.0
4  Afghanistan        Maize  1986        16875                          327.0

In [ ]:
yield_df.describe()

Year    hg/ha_yield  average_rain_fall_mm_per_year
count  25385.000000   25385.000000                   25385.000000
mean    2001.278787   68312.278353                    1254.849754
std        9.143915   75213.292733                     804.449430
min     1985.000000      50.000000                      51.000000
25%     1994.000000   17432.000000                     630.000000
50%     2001.000000   38750.000000                    1150.000000
75%     2009.000000   94286.000000                    1761.000000
max     2016.000000  554855.000000                    3240.000000

### **WORKING ON PESTICIDES DATA**

In [213]:
df_pes = pd.read_csv('pesticides.csv')
df_pes.head()

Domain     Area Element                Item  Year  \
0  Pesticides Use  Albania     Use  Pesticides (total)  1990   
1  Pesticides Use  Albania     Use  Pesticides (total)  1991   
2  Pesticides Use  Albania     Use  Pesticides (total)  1992   
3  Pesticides Use  Albania     Use  Pesticides (total)  1993   
4  Pesticides Use  Albania     Use  Pesticides (total)  1994   

                           Unit  Value  
0  tonnes of active ingredients  121.0  
1  tonnes of active ingredients  121.0  
2  tonnes of active ingredients  121.0  
3  tonnes of active ingredients  121.0  
4  tonnes of active ingredients  201.0

In [214]:
# renaming and dropping unnecessary columns
df_pes = df_pes.rename(index=str, columns={"Value": "pesticides_tonnes"})
df_pes = df_pes.drop(['Element','Domain','Unit','Item'], axis=1)
df_pes.head()

Area  Year  pesticides_tonnes
0  Albania  1990              121.0
1  Albania  1991              121.0
2  Albania  1992              121.0
3  Albania  1993              121.0
4  Albania  1994              201.0

In [215]:
df_pes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4349 entries, 0 to 4348
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Area               4349 non-null   object 
 1   Year               4349 non-null   int64  
 2   pesticides_tonnes  4349 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 135.9+ KB


In [216]:
# merging Pesticides dataframe with yield dataframe 
yield_df = pd.merge(yield_df, df_pes, on=['Year','Area'])
yield_df.shape

(18949, 6)

In [ ]:
yield_df.head()

Area         Item  Year  hg/ha_yield  average_rain_fall_mm_per_year  \
0  Albania        Maize  1990        36613                         1485.0   
1  Albania     Potatoes  1990        66667                         1485.0   
2  Albania  Rice, paddy  1990        23333                         1485.0   
3  Albania      Sorghum  1990        12500                         1485.0   
4  Albania     Soybeans  1990         7000                         1485.0   

   pesticides_tonnes  
0              121.0  
1              121.0  
2              121.0  
3              121.0  
4              121.0

### **WORKING ON TEMPERATURE DATA**

In [217]:
# now working on temperature data
avg_temp=  pd.read_csv('temp.csv')
avg_temp.head()

year        country  avg_temp
0  1849  Côte D'Ivoire     25.58
1  1850  Côte D'Ivoire     25.52
2  1851  Côte D'Ivoire     25.67
3  1852  Côte D'Ivoire       NaN
4  1853  Côte D'Ivoire       NaN

In [218]:
avg_temp = avg_temp.rename(index=str, columns={"year": "Year", "country":'Area'})
avg_temp.head()

Year           Area  avg_temp
0  1849  Côte D'Ivoire     25.58
1  1850  Côte D'Ivoire     25.52
2  1851  Côte D'Ivoire     25.67
3  1852  Côte D'Ivoire       NaN
4  1853  Côte D'Ivoire       NaN

In [219]:
avg_temp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 71311 entries, 0 to 71310
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Year      71311 non-null  int64  
 1   Area      71311 non-null  object 
 2   avg_temp  68764 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.2+ MB


In [220]:
avg_temp=avg_temp.dropna()

In [221]:
avg_temp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 68764 entries, 0 to 71310
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Year      68764 non-null  int64  
 1   Area      68764 non-null  object 
 2   avg_temp  68764 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.1+ MB


In [222]:
yield_df = pd.merge(yield_df,avg_temp, on=['Area','Year'])
yield_df.head()

Area         Item  Year  hg/ha_yield  average_rain_fall_mm_per_year  \
0  Albania        Maize  1990        36613                         1485.0   
1  Albania     Potatoes  1990        66667                         1485.0   
2  Albania  Rice, paddy  1990        23333                         1485.0   
3  Albania      Sorghum  1990        12500                         1485.0   
4  Albania     Soybeans  1990         7000                         1485.0   

   pesticides_tonnes  avg_temp  
0              121.0     16.37  
1              121.0     16.37  
2              121.0     16.37  
3              121.0     16.37  
4              121.0     16.37

In [223]:
yield_df.shape

(28242, 7)

In [224]:
yield_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28242 entries, 0 to 28241
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Area                           28242 non-null  object 
 1   Item                           28242 non-null  object 
 2   Year                           28242 non-null  int64  
 3   hg/ha_yield                    28242 non-null  int64  
 4   average_rain_fall_mm_per_year  28242 non-null  float64
 5   pesticides_tonnes              28242 non-null  float64
 6   avg_temp                       28242 non-null  float64
dtypes: float64(3), int64(2), object(2)
memory usage: 1.7+ MB


### **SHOWING SOME BASIC INFO**

In [225]:
yield_df.groupby('Item').count()

Area  Year  hg/ha_yield  average_rain_fall_mm_per_year  \
Item                                                                           
Cassava               2045  2045         2045                           2045   
Maize                 4121  4121         4121                           4121   
Plantains and others   556   556          556                            556   
Potatoes              4276  4276         4276                           4276   
Rice, paddy           3388  3388         3388                           3388   
Sorghum               3039  3039         3039                           3039   
Soybeans              3223  3223         3223                           3223   
Sweet potatoes        2890  2890         2890                           2890   
Wheat                 3857  3857         3857                           3857   
Yams                   847   847          847                            847   

                      pesticides_tonnes  avg_temp  
Item                                               
Cassava                            2045      2045  
Maize                              4121      4121  
Plantains and others                556       556  
Potatoes                           4276      4276  
Rice, paddy                        3388      3388  
Sorghum                            3039      3039  
Soybeans                           3223      3223  
Sweet potatoes                     2890      2890  
Wheat                              3857      3857  
Yams                                847       847

In [226]:
yield_df['Area'].nunique()

101

In [227]:
yield_df.groupby(['Area'],sort=True)['hg/ha_yield'].sum().nlargest(10)

Area
India             327420324
Brazil            167550306
Mexico            130788528
Japan             124470912
Australia         109111062
Pakistan           73897434
Indonesia          69193506
United Kingdom     55419990
Turkey             52263950
Spain              46773540
Name: hg/ha_yield, dtype: int64

In [228]:
yield_df.groupby(['Item','Area'],sort=True)['hg/ha_yield'].sum().nlargest(10)

Item            Area          
Cassava         India             142810624
Potatoes        India              92122514
                Brazil             49602168
                United Kingdom     46705145
                Australia          45670386
Sweet potatoes  India              44439538
Potatoes        Japan              42918726
                Mexico             42053880
Sweet potatoes  Mexico             35808592
                Australia          35550294
Name: hg/ha_yield, dtype: int64

In [229]:
yield_df.head()

Area         Item  Year  hg/ha_yield  average_rain_fall_mm_per_year  \
0  Albania        Maize  1990        36613                         1485.0   
1  Albania     Potatoes  1990        66667                         1485.0   
2  Albania  Rice, paddy  1990        23333                         1485.0   
3  Albania      Sorghum  1990        12500                         1485.0   
4  Albania     Soybeans  1990         7000                         1485.0   

   pesticides_tonnes  avg_temp  
0              121.0     16.37  
1              121.0     16.37  
2              121.0     16.37  
3              121.0     16.37  
4              121.0     16.37

### **ENCODING, SCALING AND EXTRACTING FEATURES AND LABELS**

In [230]:
from sklearn.preprocessing import OneHotEncoder
yield_df_onehot = pd.get_dummies(yield_df, columns=['Area',"Item"], prefix = ['Country',"Item"])
yield_df_onehot.head()

Year  hg/ha_yield  average_rain_fall_mm_per_year  pesticides_tonnes  \
0  1990        36613                         1485.0              121.0   
1  1990        66667                         1485.0              121.0   
2  1990        23333                         1485.0              121.0   
3  1990        12500                         1485.0              121.0   
4  1990         7000                         1485.0              121.0   

   avg_temp  Country_Albania  Country_Algeria  Country_Angola  \
0     16.37                1                0               0   
1     16.37                1                0               0   
2     16.37                1                0               0   
3     16.37                1                0               0   
4     16.37                1                0               0   

   Country_Argentina  Country_Armenia  ...  Item_Cassava  Item_Maize  \
0                  0                0  ...             0           1   
1                  0                0  ...             0           0   
2                  0                0  ...             0           0   
3                  0                0  ...             0           0   
4                  0                0  ...             0           0   

   Item_Plantains and others  Item_Potatoes  Item_Rice, paddy  Item_Sorghum  \
0                          0              0                 0             0   
1                          0              1                 0             0   
2                          0              0                 1             0   
3                          0              0                 0             1   
4                          0              0                 0             0   

   Item_Soybeans  Item_Sweet potatoes  Item_Wheat  Item_Yams  
0              0                    0           0          0  
1              0                    0           0          0  
2              0                    0           0          0  
3              0                    0           0          0  
4              1                    0           0          0  

[5 rows x 116 columns]

In [231]:
features=yield_df_onehot.loc[:, yield_df_onehot.columns != 'hg/ha_yield'].values
label=yield_df['hg/ha_yield'].values


In [232]:
features = features.drop(['Year'], axis=1)
features.head()

AttributeError: ignored

In [233]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
features=scaler.fit_transform(features) 

In [234]:
features.shape

(28242, 115)

In [235]:
label.shape

(28242,)

# **WORKING ON FIRST 10K DATA**

In [354]:
features_10k=features[:10001, :]
label_10k=label[:10001]

In [355]:
from sklearn.model_selection import train_test_split
train_data, test_data, train_labels, test_labels = train_test_split(features_10k, label_10k, test_size=0.2, random_state=0)

In [356]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
regressor_linear_10k=LinearRegression()
regressor_linear_10k.fit(train_data, train_labels)
regressor_decision_tree_10k=DecisionTreeRegressor(random_state=0)
regressor_decision_tree_10k.fit(train_data, train_labels)


DecisionTreeRegressor(random_state=0)

In [357]:
linear_pred_10k=regressor_linear_10k.predict(test_data)
tree_pred_10k=regressor_decision_tree_10k.predict(test_data)

#### **Evaluating model**

In [358]:
from sklearn.metrics import r2_score
r2_linear_10k = r2_score(test_labels,linear_pred_10k)
r2_tree_10k=r2_score(test_labels, tree_pred_10k)
print("R2 Scores\nLinear Regression:", r2_linear_10k, "\nDecision Tree Regressor:", r2_tree_10k)

R2 Scores
Linear Regression: 0.7274553767958128 
Decision Tree Regressor: 0.9739029387864919


In [359]:
from sklearn.metrics import mean_absolute_error
mae_linear_10k=mean_absolute_error(test_labels, linear_pred_10k)
mae_tree_10k=mean_absolute_error(test_labels, tree_pred_10k)
print("Mean Absolute Error\nLinear Regression:", mae_linear_10k, "\nDecision Tree Regressor:", mae_tree_10k)

Mean Absolute Error
Linear Regression: 29083.418290854574 
Decision Tree Regressor: 3951.87856071964


In [360]:
print(np.concatenate((linear_pred_10k.reshape(len(linear_pred_10k), 1), test_labels.reshape(len(test_labels), 1)) ,1)[:15])

[[ 70208.  71151.]
 [226144. 289220.]
 [175712. 113330.]
 [ 56544.  52536.]
 [  2496.  15898.]
 [151232.  18998.]
 [ 78976. 100747.]
 [ 52960.  89302.]
 [171648. 140264.]
 [ 15840.  18118.]
 [ 54400.  18740.]
 [236960. 300394.]
 [176480. 133367.]
 [ 51712.  92109.]
 [103520.  90385.]]


In [361]:
print(np.concatenate((tree_pred_10k.reshape(len(tree_pred_10k), 1), test_labels.reshape(len(test_labels), 1)) ,1)[:20])

[[ 70098.  71151.]
 [289220. 289220.]
 [131888. 113330.]
 [ 52536.  52536.]
 [ 15898.  15898.]
 [ 18111.  18998.]
 [121002. 100747.]
 [111840.  89302.]
 [140264. 140264.]
 [ 18118.  18118.]
 [ 18974.  18740.]
 [303832. 300394.]
 [133367. 133367.]
 [ 92109.  92109.]
 [ 90385.  90385.]
 [ 35822.  38994.]
 [416339. 374583.]
 [221778. 111171.]
 [ 15533.  15533.]
 [ 48038.  48388.]]


# **WORKING ON FIRST 20K ROWS**

In [362]:
features_20k=features[:20001, :]
label_20k=label[:20001]

In [363]:
train_data, test_data, train_labels, test_labels = train_test_split(features_20k, label_20k, test_size=0.2, random_state=0)

In [365]:
regressor_linear_20k=LinearRegression()
regressor_linear_20k.fit(train_data, train_labels)
regressor_decision_tree_20k=DecisionTreeRegressor(random_state=0)
regressor_decision_tree_20k.fit(train_data, train_labels)

DecisionTreeRegressor(random_state=0)

In [366]:
linear_pred_20k=regressor_linear_20k.predict(test_data)
tree_pred_20k=regressor_decision_tree_20k.predict(test_data)

#### **EVALUATING MODELS**

In [367]:
from sklearn.metrics import mean_absolute_error
mae_linear_20k=mean_absolute_error(test_labels, linear_pred_20k)
mae_tree_20k=mean_absolute_error(test_labels, tree_pred_20k)
print("Mean Absolute Error\nLinear Regression:", mae_linear_20k, "\nDecision Tree Regressor:", mae_tree_20k)

Mean Absolute Error
Linear Regression: 29378.949262684328 
Decision Tree Regressor: 3202.791552111972


In [368]:
from sklearn.metrics import r2_score
r2_linear_20k = r2_score(test_labels,linear_pred_20k)
r2_tree_20k=r2_score(test_labels, tree_pred_20k)
print("R2 Scores\nLinear Regression:", r2_linear_20k, "\nDecision Tree Regressor:", r2_tree_20k)

R2 Scores
Linear Regression: 0.7442017357917893 
Decision Tree Regressor: 0.9824303086459019


In [369]:
print(np.concatenate((linear_pred_20k.reshape(len(linear_pred_20k), 1), test_labels.reshape(len(test_labels), 1)) ,1)[:15])

[[ 24112.  38910.]
 [108736.  19455.]
 [173088. 226577.]
 [ 63072.  18025.]
 [  2560.  32680.]
 [-39424.   8000.]
 [ 18576.  24761.]
 [119904.  80643.]
 [185392. 343433.]
 [ 85008.  30279.]
 [ 33456.   8443.]
 [-26416.   3976.]
 [155488.  74061.]
 [ 71376.  65551.]
 [179568. 136118.]]


In [370]:
print(np.concatenate((tree_pred_20k.reshape(len(tree_pred_20k), 1), test_labels.reshape(len(test_labels), 1)) ,1)[:20])

[[ 29408.  38910.]
 [ 20000.  19455.]
 [226577. 226577.]
 [ 18025.  18025.]
 [ 26876.  32680.]
 [  8876.   8000.]
 [ 24761.  24761.]
 [ 80643.  80643.]
 [343433. 343433.]
 [ 30279.  30279.]
 [  8443.   8443.]
 [  2793.   3976.]
 [ 95560.  74061.]
 [ 65072.  65551.]
 [136118. 136118.]
 [ 90385.  90385.]
 [ 28226.  28226.]
 [447083. 460711.]
 [ 77391.  76928.]
 [ 14815.  14800.]]


# **WORKING ON WHOLE DATASET**

In [371]:
features_whole=features[:, :]
label_whole=label[:]

In [372]:
train_data, test_data, train_labels, test_labels = train_test_split(features_whole, label_whole, test_size=0.2, random_state=0)

In [373]:
regressor_linear_whole=LinearRegression()
regressor_linear_whole.fit(train_data, train_labels)
regressor_decision_tree_whole=DecisionTreeRegressor(random_state=0)
regressor_decision_tree_whole.fit(train_data, train_labels)

DecisionTreeRegressor(random_state=0)

In [374]:
linear_pred_whole=regressor_linear_whole.predict(test_data)
tree_pred_whole=regressor_decision_tree_whole.predict(test_data)

#### **EVALUATING MODELS**

In [375]:
from sklearn.metrics import r2_score
r2_linear_whole = r2_score(test_labels,linear_pred_whole)
r2_tree_whole=r2_score(test_labels, tree_pred_whole)
print("R2 Scores\nLinear Regression:", r2_linear_whole, "\nDecision Tree Regressor:", r2_tree_whole)

R2 Scores
Linear Regression: 0.7597282287564799 
Decision Tree Regressor: 0.9816728500821664


In [376]:
from sklearn.metrics import mean_absolute_error
mae_linear_whole=mean_absolute_error(test_labels, linear_pred_whole)
mae_tree_whole=mean_absolute_error(test_labels, tree_pred_whole)
print("Mean Absolute Error\nLinear Regression:", mae_linear_whole, "\nDecision Tree Regressor:", mae_tree_whole)

Mean Absolute Error
Linear Regression: 29261.579394583114 
Decision Tree Regressor: 3751.1761373694458


In [378]:
# np.set_printoptions(precision=5)
print(np.concatenate((linear_pred_whole.reshape(len(linear_pred_whole), 1), test_labels.reshape(len(test_labels), 1)) ,1)[:15])

[[ 3.09760e+04  3.31570e+04]
 [ 1.22568e+05  9.23730e+04]
 [ 1.57280e+04  3.39190e+04]
 [ 1.77440e+04  3.12140e+04]
 [-2.24000e+02  1.60100e+04]
 [ 1.77216e+05  1.54928e+05]
 [ 1.84800e+04  1.10290e+04]
 [ 6.46560e+04  3.64290e+04]
 [ 1.91056e+05  1.83405e+05]
 [ 1.13680e+05  1.05267e+05]
 [ 1.87192e+05  1.39286e+05]
 [-4.52880e+04  2.15200e+04]
 [ 5.71200e+04  3.47590e+04]
 [ 2.45952e+05  3.54317e+05]
 [-1.17520e+04  4.99200e+03]]


In [379]:
print(np.concatenate((tree_pred_whole.reshape(len(tree_pred_whole), 1), test_labels.reshape(len(test_labels), 1)) ,1)[:20])

[[ 33157.  33157.]
 [ 87717.  92373.]
 [ 43022.  33919.]
 [ 31214.  31214.]
 [ 16364.  16010.]
 [115775. 154928.]
 [ 12843.  11029.]
 [ 36429.  36429.]
 [183405. 183405.]
 [105267. 105267.]
 [157368. 139286.]
 [ 21520.  21520.]
 [ 34759.  34759.]
 [354317. 354317.]
 [  4992.   4992.]
 [ 68826.  62941.]
 [226963. 226963.]
 [ 90080.  90080.]
 [ 18654.  18654.]
 [ 39602.  39602.]]
